### ISSUE TITLE
Error Encountered: Invalid UTF-8 Encoding in YAML During Asset Import Process

### ISSUE THREAD

**Issue by iSaadSalman** [statamic/eloquent-driver#225]
### Bug Description

When executing the command `php please eloquent:import-assets`, encountering an error related to invalid UTF-8 encoding in YAML while trying to import assets.

### Steps to Reproduce

1. Run the command: `php please eloquent:import-assets`.
2. Answer 'yes' to import asset containers.
3. When prompted to import assets, answer 'yes' again.
4. Observe the error encountered during the asset import process.

### Expected Behavior

Expect the asset import to proceed without encountering a YAML encoding error.

### Error Details

```
Do you want to import asset containers? (yes/no) [no]:
 > yes

1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Asset containers imported

Do you want to import assets? (yes/no) [no]:
 > yes

0/8765 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
Statamic\Yaml\ParseException 

The YAML value does not appear to be valid UTF-8.

at storage/statamic/tmp/yaml/1000_7625b72c46.jpg:-1
    1▕ ����\JFIF\\�\�\\��\;CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 90
    2▕ ��\C\
    3▕ 

    4▕ 

    5▕ 


    6▕ 
    7▕ 


       ��\C
    8▕ 

    9▕ ����"\��\\\\\\\\\\\
```

### Additional Details

- Statamic Version: 4.21
- Eloquent Driver Version: 3.0.0
- PHP Version: 8.2.12

**Comment by ryanmitchell** [comment]
There has been a lot of changes to directory listing and imports at this PR:
https://github.com/statamic/eloquent-driver/pull/224

It should solve this issue too

**Comment by Bracketstech** [comment]
@ryanmitchell 
I tried the latest (v3.0.1) but I'm still facing the issue

<img width="1407" alt="Screen Shot 2024-01-14 at 12 34 14 PM" src="https://github.com/statamic/eloquent-driver/assets/77781410/3c4546a9-a6d5-4f4a-a37d-995b5d8f0c4d">

**Comment by ryanmitchell** [comment]
Thanks. I plan to look into this further next week.

**Comment by Bracketstech** [comment]
@ryanmitchell Any ideas on how I can try to resolve it from my end?

**Comment by ryanmitchell** [comment]
I've opened a PR here - let me know if this works for you: https://github.com/statamic/eloquent-driver/pull/227

**Comment by Bracketstech** [comment]
@ryanmitchell Thanks so much. I tested your PR and after running php please eloquent:import-assets. it seems to have imported the media in DB. I will test further but for now it seems ok
