### ISSUE TITLE
Content API: Selecting Fields not working / error

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/eloquent-driver#26]
## Bug Description
If you try to select just specific fields (exactly as described [in the documentation](https://statamic.dev/content-api#selecting-fields)), nothing happens or an error will be thrown.

#### Request
`http://statamic.test/api/collections/newsletters/entries?fields=title`
#### Response
<img width="854" alt="Bildschirmfoto 2021-08-09 um 14 00 31" src="https://user-images.githubusercontent.com/15997450/128702931-d87d3f4c-2760-49ee-986f-133493367ae0.png">
I would expect only the `title` attribute of each entry shown here.

#### Request
`http://statamic.test/api/collections/newsletters/entries?fields=id`
or
`http://statamic.test/api/collections/newsletters/entries?fields=date`
or
`http://statamic.test/api/collections/newsletters/entries?fields=uri`
#### Response
**Error: Call to a member function cascade() on null**
<img width="1222" alt="Bildschirmfoto 2021-08-09 um 14 09 34" src="https://user-images.githubusercontent.com/15997450/128703857-2be24ab8-a7fd-4ddb-851c-959b187dc6dd.png">

## Environment

Statamic 3.1.32 Pro
Laravel 8.40.0
PHP 7.4.19
statamic/collaboration 0.1.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Smef** [comment]
This is something we're experiencing as well. Including the "collection" field seems to be a workaround for now, but a real fix would be great!

**Comment by ryanmitchell** [comment]
I think the solution will be to always select collection even when it's not asked for. But yep leave it with me and I'll try and come up with something before the next release.

**Comment by ryanmitchell** [comment]
I've opened a [pull request here](https://github.com/statamic/eloquent-driver/pull/183) which should solve the issue, though I need to spend some time sitting on it to decide if (a) there isnt a better way, (b) this doesnt affect other areas of the driver

**Comment by Smef** [comment]
It turns out adding the collection field doesn't actually resolve this. The query doesn't fail, but all the fields of the entry are null when the collection field is included.

**Comment by ryanmitchell** [comment]
@Smef did you try applying the changes made here: https://github.com/statamic/eloquent-driver/pull/183

**Comment by Smef** [comment]
I tried updating the EntryQueryBuilder.php file with the changes in that PR. It didn't seem to make a difference with the returned data.
Here's an example
`fields=title,price_base`
returns:
```
{
    "data": [
        {
            "title": "magnam velit accusamus et eius",
            "price_base": 37.25
        }
    ],
...
```

adding id and collection:
`fields=id,collection,title,price_base`
```
{
    "data": [
        {
            "id": 332,
            "collection": {
                "title": "Products",
                "handle": "products"
            },
            "title": null,
            "price_base": null
        }
...
```

**Comment by ryanmitchell** [comment]
@Smef works fine for me with the PR - double check you copied everything over fully:

visiting: /api/collections/pages/entries?fields=id,title,template,shares,content

```json
{
    "data": [
        {
            "id": "4a8b8690-55c6-426d-8d08-2bc73df230ab",
            "title": "Articles",
            "template": "articles.index",
            "shares": 53,
            "content": "<p>These are my various writings. Some might say they are cool.222</p>\n"
        },
        {
            "id": "56f274ce-a723-4913-bae6-1d13833c356f",
            "title": "Home",
            "template": "home",
            "shares": 99,
            "content": "<p>I see a bad-ass mother who don't take no crap off of nobody.</p>\n"
        },
        {
            "id": "62136fa2-9e5c-4c38-a894-a2753f02f5ff",
            "title": "About",
            "template": "page",
            "shares": 54,
            "content": "<p>I'm just a kid living in the 90's, writing articles in his secret public journal wonder if someday, somewhere in the future, they will be read by someone.</p>\n"
        },
        {
            "id": "b9e4bfe3-9c12-4553-b7ef-f43c22ffaa63",
            "title": "Articles",
            "template": "articles.index",
            "shares": 21,
            "content": "<p>These are my various writings. Some might say they are cool.</p>\n"
        },
        {
            "id": "f5a53468-017e-4725-b5b6-a745df7e94cb",
            "title": "Topics",
            "template": "topics/index",
            "shares": 37,
            "content": null
        },
        {
            "id": "home",
            "title": "Home",
            "template": "home",
            "shares": 98,
            "content": "<p>I see a bad-ass mother who don't take no crap off of nobody.</p>\n"
        }
    ],
```

**Comment by Smef** [comment]
Ah! I found the problem. I had accidentally updated the Statamic EntryQueryBuilder and not the eloquent-driver EntryQueryBuilder file.

Yes, this update resolved the issue, and I'm able to query the ID and slug fields without including the collection.

Thanks!
